import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/component/Navbar";
import { roboto } from "@/fonts";



export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <Navbar/>
        <main className="pt-10">{children}</main>
      </body>
    </html>
  );
}
