import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/component/Navbar";
import { roboto } from "@/fonts";
import Footer from "@/component/Footer";
import { ThemeProvider } from "@/contextApi/ThemeContex";



export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} transition-colors duration-500`}
      >
        <ThemeProvider>
          <Navbar/>
          <main className="pt-0">{children}</main>
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
